---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pre-commit: "https://raw.githubusercontent.com/CowDogMoo/taskfile-templates/main/pre-commit/Taskfile.yaml"

tasks:
  default:
    desc: Run all checks
    cmds:
      - task: pre-commit:run-pre-commit
      - task: test

  test:
    desc: Run pytest
    cmds:
      - python3 -m pytest tests/ -x -q
